In [1]:
import numpy as np
import string

## Exercise 1:
Define the matrices below using NumPy. Use the np.array() method.
<img src=https://img-c.udemycdn.com/redactor/raw/article_lecture/2020-10-30_01-20-10-843e77c1e2bc2929177b77ea963fa835.png>
Reminder: we can notice that the matrices B and C are square matrices, since the number of rows is equal to the number of columns.


In [2]:
ex1A = np.array([[1,2,3],[2,1,-1]])
ex1A

array([[ 1,  2,  3],
       [ 2,  1, -1]])

In [3]:
ex1B = np.array([[1,-2,0],[3,0,1],[4,5,6]])
ex1B

array([[ 1, -2,  0],
       [ 3,  0,  1],
       [ 4,  5,  6]])

In [4]:
ex1C = np.array([[1,2,3],[4,5,6],[7,8,9]])
ex1C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
ex1D = np.array([[1],[4],[-3]])
ex1D

array([[ 1],
       [ 4],
       [-3]])

----------------------------------------------------------------------------------------------------------------------------
## Exercise 2:
Define the matrices below using NumPy. Use the np.array() method.
<img src = https://img-c.udemycdn.com/redactor/raw/article_lecture/2020-10-30_01-22-51-956b3852646c780d0f9399eec5e56ed6.png>

In [6]:
ex2A = np.array([[1],[2],[3],[4],[5],[6]])
ex2A

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
ex2B = np.array([1,0,3,-10])
ex2B

array([  1,   0,   3, -10])

In [8]:
ex2B = np.array([1,2,3,4,5])
ex2B

array([1, 2, 3, 4, 5])

----------------------------------------------------------------------------------------------------------------------------
## Exercise 3:
Define the matrices below using NumPy. Use the np.array() method.
<img src = https://img-c.udemycdn.com/redactor/raw/article_lecture/2020-10-30_01-26-29-eae8695f549702e05763a13a7f5f3400.png>
The matrices I2, I3, I6 are called as Squared Identities Matrices, where each aij = 1 to every i = j and aij = 0 to every i different from j. So, we know that the main diagonal will be filled with 1 and the other positions on the matrix will have 0.

In [9]:
ex3A = np.zeros((2,2), dtype = int)
ex3A

array([[0, 0],
       [0, 0]])

In [10]:
ex3B = np.zeros((3,5), dtype = int)
ex3B

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
ex3C = np.ones((5,5), dtype = int)
ex3C

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
ex4D =  np.eye(2, dtype = int)
ex4D

array([[1, 0],
       [0, 1]])

In [13]:
ex4E =  np.eye(3, dtype = int)
ex4E

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [14]:
ex4F =  np.eye(6, dtype = int)
ex4F

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

----------------------------------------------------------------------------------------------------------------------------
## Exercise 4:
Define the triangular matrices below using the NumPy. Use the np.triu() and np.tril() methods.
<img src = https://img-c.udemycdn.com/redactor/raw/article_lecture/2020-10-30_01-29-42-de11c3da6bb33565896430b2409dac25.png>


In [15]:
ex4A = np.array(range(1,10)).reshape(3,3)
np.triu(ex4A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [16]:
ex4B = np.array(range(1,10)).reshape(3,3)
np.tril(ex4A)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [17]:
ex4A = np.array(range(100,125)).reshape(5,5)
np.triu(ex4A)

array([[100, 101, 102, 103, 104],
       [  0, 106, 107, 108, 109],
       [  0,   0, 112, 113, 114],
       [  0,   0,   0, 118, 119],
       [  0,   0,   0,   0, 124]])

----------------------------------------------------------------------------------------------------------------------------
## Exercise 5:
Define the matrices below using NumPy. Use the np.diag() and np.array() methods.
<img src = https://img-c.udemycdn.com/redactor/raw/article_lecture/2020-10-30_01-31-51-fba26c0136181c2dc66e0bdd9893ae3d.png>

In [18]:
ex5A = np.ones((3,3),dtype = int)
values = [7,1,-1]
for i in range(0,3):
    ex5A[i] = ex5A[i] * values[i]
np.diag(np.diag(ex5A))

array([[ 7,  0,  0],
       [ 0,  1,  0],
       [ 0,  0, -1]])

In [19]:
ex5B = np.ones((4,4), dtype = int)*3
np.diag(np.diag(ex5B))

array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [20]:
ex5A = np.ones((5,5),dtype = int)
values = [-5,-4,-3,-2,-1]
for i in range(0,5):
    ex5A[i] = ex5A[i] * values[i]
np.diag(np.diag(ex5A))

array([[-5,  0,  0,  0,  0],
       [ 0, -4,  0,  0,  0],
       [ 0,  0, -3,  0,  0],
       [ 0,  0,  0, -2,  0],
       [ 0,  0,  0,  0, -1]])

---
## Exercise 6:
Define the matrices A and B given below and obtain A+B.

<img src = https://img-c.udemycdn.com/redactor/raw/article_lecture/2020-10-30_01-33-56-855511f2f4dea3bd2ef789ca0560463a.png>

In [21]:
ex6A = np.array(([10,11],[5,1],[-1,4]))
ex6A

array([[10, 11],
       [ 5,  1],
       [-1,  4]])

In [22]:
ex6B = np.array(([1,25],[3,4],[0,-10]))
ex6B

array([[  1,  25],
       [  3,   4],
       [  0, -10]])

In [25]:
ex6_sum = ex6A + ex6B
ex6_sum

array([[11, 36],
       [ 8,  5],
       [-1, -6]])