## Exercise 1:
A numpy object has attributes and methods inherited from the class (numpy.ndarray). Creat an array and inspect the following attributes:


Shape: A tuple containing a number of elements (size) in each dimension of the array;

Size: Total number of elements in the array;

ndim: Number of dimensions (axes);

nbytes: Number of bytes used to store the data;

dtype: The data type of the elements in the array;


Implementation example:

    import numpy as np
    array = np.array([1, 2, 3, 4])
    print('Shape: ', array.shape)

In [1]:
import numpy as np
ex1 = np.array([1, 2, 3, 4])

print(f"Shape: {ex1.shape}")
print(f"Size: {ex1.size}")
print(f"Dimension: {ex1.ndim}")
print(f"Number of bytes: {ex1.nbytes}")
print(f"Data type: {ex1.dtype}")

Shape: (4,)
Size: 4
Dimension: 1
Number of bytes: 16
Data type: int32


----------------------------------------------------------------------------------------------------------------------------
## Exercise 2:   
Based on the previous exercise, create a function that can receive an array and shows on the screen its attributes. Check if the insert argument is, indeed, a numpy object. You can also use a built-in type () function to verify the object' class

In [2]:
def attributes(array):
    if type(array) == type(np.array(0)):
        print(f"Shape: {array.shape}")
        print(f"Size: {array.size}")
        print(f"Dimension: {array.ndim}")
        print(f"Number of bytes: {array.nbytes}")
        print(f"Data type: {array.dtype}")
    else:
        print("The value inserted is not a numpy array")

In [3]:
attributes(np.array([1, 2, 3, 4]))

Shape: (4,)
Size: 4
Dimension: 1
Number of bytes: 16
Data type: int32


In [4]:
attributes([1, 2, 3, 4])

The value inserted is not a numpy array


----------------------------------------------------------------------------------------------------------------------------

## Exercise 3: 
Use the np.array() function to creat the one-dimensioned arrays listed below:


a) Use a list as an argument and obtain:

    array([-1,  4,  7,  9])


b) Use the range() function and obtain:

    array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


Use a tuple as an argument and obtain:

    array([10, 11, 12, 13, 14])


d) Use the range() function and obtain:

    array([1990, 1995, 2000, 2005, 2010, 2015, 2020])


e) Use the range() function and obtain:

    array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920, 1910, 1900])


f) Obtain:


    array(100)

In [5]:
lista = [-1, 4, 7, 9]
ex3_A = np.array(lista)
print(ex3_A)

[-1  4  7  9]


In [6]:
ex3_B = np.array(list(range(1,11)))
print(ex3_B)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
tupple = (10,11,12,13,14)
ex3_C = np.array(tupple)
print(ex3_C)

[10 11 12 13 14]


In [8]:
ex3_D = np.array(list(range(1990,2021,5)))
print(ex3_D)

[1990 1995 2000 2005 2010 2015 2020]


In [9]:
ex3_E = np.array(list(range(2020,1899,-10)))
print(ex3_E)

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]


In [10]:
ex3_F = np.array(100)
print(ex3_F)

100


----------------------------------------------------------------------------------------------------------------------------

## Exercise 4:
The np.ones() function allows you to create an array filled with the number 1 in all your entries. We can specify as arguments the shape and the kind of dtype of the array. Use this function to create the following arrays:

a)


    array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


b)


    array([[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]])


c)


    array([[1., 1.],
           [1., 1.],
           [1., 1.]])




In [11]:
ex4_A = np.ones(10)
print(ex4_A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
ex4_B = np.ones((4,4))
print(ex4_B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
ex4_C = np.ones((3,2))
print(ex4_C)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 5: 
The np.zeros() function allows you to create an array filled with the number 0 in all your entries. We can specify as arguments the shape and the kind of dtype of the array (default is the float). Use this function to create the following arrays:

a)

    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b)

    array([[0., 0.],       
          [0., 0.]])  


c)

    array([[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]])

In [14]:
ex5_A = np.zeros(10)
print(ex5_A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
ex5_B = np.zeros((2,2))
print(ex5_B)

[[0. 0.]
 [0. 0.]]


In [16]:
ex5_C = np.zeros((4,6))
print(ex5_C)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 6:
Create the following arrays:


a)

    array([[10],
           [15],
           [20],
           [25],
           [30],
           [35],
           [40],
           [45]])


b)


    array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])


c)


    array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
           [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
           [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
           [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
           [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])


Tip: use np.arange() or np.array(range()).

In [24]:
ex6_A = np.arange(10,46,5).reshape(8,1)
print(ex6_A)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]


In [25]:
ex6_B = np.arange(-50,-4,5)
print(ex6_B)

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]


In [28]:
ex6_B = np.arange(50,149,2).reshape(5,10)
print(ex6_B)

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 7: 
Use the np.full(shape, fill_value, dtype) function to create the following arrays. This function allows you to create an array with a user-defined shape and dtype, filled with a certain value.

a)


    array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


b)


    array([[-5., -5., -5., -5.],
           [-5., -5., -5., -5.],
           [-5., -5., -5., -5.],
           [-5., -5., -5., -5.]])


c)


    array([[3, 3, 3],
           [3, 3, 3],
           [3, 3, 3]])


d)


    array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])


Tip: Another possibility would be to obtain the arrays with a different operation, by mutiplying a matrix filled with the number 1 by a certain value.

In [30]:
ex7_A = np.full((1,10), 5)
print(ex7_A)

[[5 5 5 5 5 5 5 5 5 5]]


In [32]:
ex7_B = np.full((4,4), -5)
print(ex7_B)

[[-5 -5 -5 -5]
 [-5 -5 -5 -5]
 [-5 -5 -5 -5]
 [-5 -5 -5 -5]]


In [33]:
ex7_C = np.full((3,3), 3)
print(ex7_C)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [34]:
ex7_D = np.full((10,10), 50)
print(ex7_D)

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 8: 
Define the K array and check for missing data. Use the np.isnan() function.


    array([[ nan,   1.,  10.,   0.],
           [ nan,  nan,  nan,  nan],
           [100.,  50.,  nan, -25.],
           [ 30.,  nan,  nan, 130.]])

In [47]:
ex_8 = np.array([[ np.nan,   1.,  10.,   0.],
     [ np.nan,  np.nan,  np.nan,  np.nan],
     [100.,  50.,  np.nan, -25.],
     [ 30.,  np.nan,  np.nan, 130.]])
print(np.isnan(ex_8))

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 9:

The np.linspace () function returns an array of evenly spaced numbers within a defined range. Create an array with numbers within the range [1,21] in 5 parts.


Expected return:

    array([ 1.,  6., 11., 16., 21.])

In [59]:
ex9 = np.linspace(1,21,5)
print(ex9)

[ 1.  6. 11. 16. 21.]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 10: 

The np.logspace () function returns evenly spaced numbers on a logarithmic scale. Create an array with numbers within the range [1,51] in 10 parts with the np.logspace() function.


Expected return:

    array([[1.00000000e+01],
           [3.59381366e+06],
           [1.29154967e+12],
           [4.64158883e+17],
           [1.66810054e+23],
           [5.99484250e+28],
           [2.15443469e+34],
           [7.74263683e+39],
           [2.78255940e+45],
           [1.00000000e+51]])

In [63]:
ex10 = np.logspace(1,51,10)
print(ex10.reshape(10,1))

[[1.00000000e+01]
 [3.59381366e+06]
 [1.29154967e+12]
 [4.64158883e+17]
 [1.66810054e+23]
 [5.99484250e+28]
 [2.15443469e+34]
 [7.74263683e+39]
 [2.78255940e+45]
 [1.00000000e+51]]
