In [102]:
import numpy as np
import string

## Exercise 1:
A numpy object has attributes and methods inherited from the class (numpy.ndarray). Creat an array and inspect the following attributes:


Shape: A tuple containing a number of elements (size) in each dimension of the array;

Size: Total number of elements in the array;

ndim: Number of dimensions (axes);

nbytes: Number of bytes used to store the data;

dtype: The data type of the elements in the array;


Implementation example:

    import numpy as np
    array = np.array([1, 2, 3, 4])
    print('Shape: ', array.shape)

In [1]:
ex1 = np.array([1, 2, 3, 4])

print(f"Shape: {ex1.shape}")
print(f"Size: {ex1.size}")
print(f"Dimension: {ex1.ndim}")
print(f"Number of bytes: {ex1.nbytes}")
print(f"Data type: {ex1.dtype}")

Shape: (4,)
Size: 4
Dimension: 1
Number of bytes: 16
Data type: int32


----------------------------------------------------------------------------------------------------------------------------
## Exercise 2:   
Based on the previous exercise, create a function that can receive an array and shows on the screen its attributes. Check if the insert argument is, indeed, a numpy object. You can also use a built-in type () function to verify the object' class

In [2]:
def attributes(array):
    if type(array) == type(np.array(0)):
        print(f"Shape: {array.shape}")
        print(f"Size: {array.size}")
        print(f"Dimension: {array.ndim}")
        print(f"Number of bytes: {array.nbytes}")
        print(f"Data type: {array.dtype}")
    else:
        print("The value inserted is not a numpy array")

In [3]:
attributes(np.array([1, 2, 3, 4]))

Shape: (4,)
Size: 4
Dimension: 1
Number of bytes: 16
Data type: int32


In [4]:
attributes([1, 2, 3, 4])

The value inserted is not a numpy array


----------------------------------------------------------------------------------------------------------------------------

## Exercise 3: 
Use the np.array() function to creat the one-dimensioned arrays listed below:


a) Use a list as an argument and obtain:

    array([-1,  4,  7,  9])


b) Use the range() function and obtain:

    array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


Use a tuple as an argument and obtain:

    array([10, 11, 12, 13, 14])


d) Use the range() function and obtain:

    array([1990, 1995, 2000, 2005, 2010, 2015, 2020])


e) Use the range() function and obtain:

    array([2020, 2010, 2000, 1990, 1980, 1970, 1960, 1950, 1940, 1930, 1920, 1910, 1900])


f) Obtain:


    array(100)

In [5]:
lista = [-1, 4, 7, 9]
ex3_A = np.array(lista)
print(ex3_A)

[-1  4  7  9]


In [6]:
ex3_B = np.array(list(range(1,11)))
print(ex3_B)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
tupple = (10,11,12,13,14)
ex3_C = np.array(tupple)
print(ex3_C)

[10 11 12 13 14]


In [8]:
ex3_D = np.array(list(range(1990,2021,5)))
print(ex3_D)

[1990 1995 2000 2005 2010 2015 2020]


In [9]:
ex3_E = np.array(list(range(2020,1899,-10)))
print(ex3_E)

[2020 2010 2000 1990 1980 1970 1960 1950 1940 1930 1920 1910 1900]


In [10]:
ex3_F = np.array(100)
print(ex3_F)

100


----------------------------------------------------------------------------------------------------------------------------

## Exercise 4:
The np.ones() function allows you to create an array filled with the number 1 in all your entries. We can specify as arguments the shape and the kind of dtype of the array. Use this function to create the following arrays:

a)


    array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


b)


    array([[1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.],
           [1., 1., 1., 1.]])


c)


    array([[1., 1.],
           [1., 1.],
           [1., 1.]])




In [11]:
ex4_A = np.ones(10)
print(ex4_A)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
ex4_B = np.ones((4,4))
print(ex4_B)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [13]:
ex4_C = np.ones((3,2))
print(ex4_C)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 5: 
The np.zeros() function allows you to create an array filled with the number 0 in all your entries. We can specify as arguments the shape and the kind of dtype of the array (default is the float). Use this function to create the following arrays:

a)

    array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


b)

    array([[0., 0.],       
          [0., 0.]])  


c)

    array([[0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0.]])

In [14]:
ex5_A = np.zeros(10)
print(ex5_A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
ex5_B = np.zeros((2,2))
print(ex5_B)

[[0. 0.]
 [0. 0.]]


In [16]:
ex5_C = np.zeros((4,6))
print(ex5_C)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 6:
Create the following arrays:


a)

    array([[10],
           [15],
           [20],
           [25],
           [30],
           [35],
           [40],
           [45]])


b)


    array([-50, -45, -40, -35, -30, -25, -20, -15, -10,  -5])


c)


    array([[ 50,  52,  54,  56,  58,  60,  62,  64,  66,  68],
           [ 70,  72,  74,  76,  78,  80,  82,  84,  86,  88],
           [ 90,  92,  94,  96,  98, 100, 102, 104, 106, 108],
           [110, 112, 114, 116, 118, 120, 122, 124, 126, 128],
           [130, 132, 134, 136, 138, 140, 142, 144, 146, 148]])


Tip: use np.arange() or np.array(range()).

In [17]:
ex6_A = np.arange(10,46,5).reshape(8,1)
print(ex6_A)

[[10]
 [15]
 [20]
 [25]
 [30]
 [35]
 [40]
 [45]]


In [18]:
ex6_B = np.arange(-50,-4,5)
print(ex6_B)

[-50 -45 -40 -35 -30 -25 -20 -15 -10  -5]


In [19]:
ex6_B = np.arange(50,149,2).reshape(5,10)
print(ex6_B)

[[ 50  52  54  56  58  60  62  64  66  68]
 [ 70  72  74  76  78  80  82  84  86  88]
 [ 90  92  94  96  98 100 102 104 106 108]
 [110 112 114 116 118 120 122 124 126 128]
 [130 132 134 136 138 140 142 144 146 148]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 7: 
Use the np.full(shape, fill_value, dtype) function to create the following arrays. This function allows you to create an array with a user-defined shape and dtype, filled with a certain value.

a)


    array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])


b)


    array([[-5., -5., -5., -5.],
           [-5., -5., -5., -5.],
           [-5., -5., -5., -5.],
           [-5., -5., -5., -5.]])


c)


    array([[3, 3, 3],
           [3, 3, 3],
           [3, 3, 3]])


d)


    array([[50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
           [50, 50, 50, 50, 50, 50, 50, 50, 50, 50]])


Tip: Another possibility would be to obtain the arrays with a different operation, by mutiplying a matrix filled with the number 1 by a certain value.

In [20]:
ex7_A = np.full((1,10), 5)
print(ex7_A)

[[5 5 5 5 5 5 5 5 5 5]]


In [21]:
ex7_B = np.full((4,4), -5)
print(ex7_B)

[[-5 -5 -5 -5]
 [-5 -5 -5 -5]
 [-5 -5 -5 -5]
 [-5 -5 -5 -5]]


In [22]:
ex7_C = np.full((3,3), 3)
print(ex7_C)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [23]:
ex7_D = np.full((10,10), 50)
print(ex7_D)

[[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 8: 
Define the K array and check for missing data. Use the np.isnan() function.


    array([[ nan,   1.,  10.,   0.],
           [ nan,  nan,  nan,  nan],
           [100.,  50.,  nan, -25.],
           [ 30.,  nan,  nan, 130.]])

In [24]:
ex_8 = np.array([[ np.nan,   1.,  10.,   0.],
     [ np.nan,  np.nan,  np.nan,  np.nan],
     [100.,  50.,  np.nan, -25.],
     [ 30.,  np.nan,  np.nan, 130.]])
print(np.isnan(ex_8))

[[ True False False False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True False]]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 9:

The np.linspace () function returns an array of evenly spaced numbers within a defined range. Create an array with numbers within the range [1,21] in 5 parts.


Expected return:

    array([ 1.,  6., 11., 16., 21.])

In [25]:
ex9 = np.linspace(1,21,5)
print(ex9)

[ 1.  6. 11. 16. 21.]


----------------------------------------------------------------------------------------------------------------------------

## Exercise 10: 

The np.logspace () function returns evenly spaced numbers on a logarithmic scale. Create an array with numbers within the range [1,51] in 10 parts with the np.logspace() function.


Expected return:

    array([[1.00000000e+01],
           [3.59381366e+06],
           [1.29154967e+12],
           [4.64158883e+17],
           [1.66810054e+23],
           [5.99484250e+28],
           [2.15443469e+34],
           [7.74263683e+39],
           [2.78255940e+45],
           [1.00000000e+51]])

In [26]:
ex10 = np.logspace(1,51,10)
print(ex10.reshape(10,1))

[[1.00000000e+01]
 [3.59381366e+06]
 [1.29154967e+12]
 [4.64158883e+17]
 [1.66810054e+23]
 [5.99484250e+28]
 [2.15443469e+34]
 [7.74263683e+39]
 [2.78255940e+45]
 [1.00000000e+51]]


----------------------------------------------------------------------------------------------------------------------------
## Exercise 11: 
Use the np.diag() function to build the following array:


    array([[ 5,  0,  0,  0,  0,  0],
           [ 0, 10,  0,  0,  0,  0],
           [ 0,  0, 15,  0,  0,  0],
           [ 0,  0,  0, 20,  0,  0],
           [ 0,  0,  0,  0, 25,  0],
           [ 0,  0,  0,  0,  0, 30]])

In [58]:
ex11 = np.ones((6,6))
f = 0
for i in range(5,31,5):
    ex11[f] = ex11[f]*i
    f += 1

In [61]:
print(np.diag(np.diag(ex11)))

[[ 5.  0.  0.  0.  0.  0.]
 [ 0. 10.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 20.  0.  0.]
 [ 0.  0.  0.  0. 25.  0.]
 [ 0.  0.  0.  0.  0. 30.]]


----------------------------------------------------------------------------------------------------------------------------
## Exercise 12: 
Use the np.eye() function (or even np.identity()) to obtain the following array.


    array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


Tip: this matrix is ​​defined as an identity matrix, in this case of order 10, and it assumes great relevance in several computational calculations, as we will see later.

In [67]:
np.eye(10, dtype = float)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

----------------------------------------------------------------------------------------------------------------------------
## Exercise 13: 
Obtain the sum of the elements of each array below. Use the np.sum () function. Implement a solution with "loop for", to do so, store the vectors in a list.


    import numpy as np
    array1 = np.arange(1,11)
    array2 = np.linspace(1,50,10)
    array3 = np.array(range(51))
    array4 = np.logspace(1,10,5)
    array5 = np.diag(range(5,31,5))


Expected return:


    Sum of the elements of array 1:  55
    Sum of the elements of array 2:  255.0
    Sum of the elements of array 3:  1275
    Sum of the elements of array 4:  10056552148.564463
    Sum of the elements of array 5:  105

In [71]:
ex13A = np.arange(1,11)
ex13B = np.linspace(1,50,10)
ex13C = np.array(range(51))
ex13D = np.logspace(1,10,5)
ex13E = np.diag(range(5,31,5))

In [106]:
indexs = [ex13A,ex13B,ex13C,ex13D,ex13E]

In [109]:
for index, letter in zip(indexs, string.ascii_uppercase):
    print(f"Sum of the elements of the ex13{letter}: {np.sum(index)}")

Sum of the elements of the ex13A: 55
Sum of the elements of the ex13B: 255.0
Sum of the elements of the ex13C: 1275
Sum of the elements of the ex13D: 10056552148.564463
Sum of the elements of the ex13E: 105


----------------------------------------------------------------------------------------------------------------------------
## Exercise 14:
From the matrix defined below, obtain:

    a) total sum of the elements;

    b) sum of the lines;

    c) sum of columns.


    import numpy as np
    matrix = np.array(np.random.randint(1,100,15)).reshape(5,3)

In [89]:
ex14 = np.array(np.random.randint(1,100,15)).reshape(5,3)

In [97]:
print("Total sum of the elements: ", np.sum(ex14))
print("Sum of the lines: ", np.sum(ex14, axis= 1))
print("Sum of the columns: ", np.sum(ex14, axis= 0))

Total sum of the elements:  798
Sum of the lines:  [ 82  89 134 278 215]
Sum of the columns:  [235 291 272]


----------------------------------------------------------------------------------------------------------------------------
## Exercise 15:
Obtain the maximum and minimum value of each array below. Implement a solution with a "loop for".


    import numpy as np
    array1 = np.array([-1, 10, 3, 4, 7, 27])
    array2 = np.random.randint(-100,300,30)
    array3 = np.random.randn(10)
    array4 = np.array(range(50,10,-2))


Tip: To obtain the maximum and minimium value of an array, we can use array.max() and array.min() (or max(array) and min(array)).

In [110]:
ex15A = np.array([-1, 10, 3, 4, 7, 27])
ex15B = np.random.randint(-100,300,30)
ex15C = np.random.randn(10)
ex15D = np.array(range(50,10,-2))
indexs = [ex15A,ex15B,ex15C,ex15D]

In [113]:
for index, letter in zip(indexs, string.ascii_uppercase):
    print(f"ex15{letter} | Maximum = {round(index.max(),2)} | Minimum = {round(index.min())}")

ex15A | Maximum = 27 | Minimum = -1
ex15B | Maximum = 296 | Minimum = -87
ex15C | Maximum = 1.59 | Minimum = -1
ex15D | Maximum = 50 | Minimum = 12


----------------------------------------------------------------------------------------------------------------------------
## Exercise 16: 
Create a function that receives a matrix as input and calculate:


a) Maximum value of the matrix;

b) Maximum value per column;

c) Maximum value per line;

d) Minimum value of the matrix;

e) Minimum value per column;

f) Minimum value per line.


Example of return for the matrix defined below:


Input:

    matrix = np.random.randint(-1000,1000,50).reshape(10,5)
    info_array(array)

Output:

    Maximum value of the matrix:  987
    Maximum value per column:  [959 987 597 748 719]
    Maximum value per line:  [ 987  312  982  204  719  689  101  793 -460  959]
    Minimum value of the matrix:  -969
    Minimum value per column:  [-878 -966 -969 -884 -881]
    Minimum value per line:  [  30 -878 -335 -863  -40 -289 -660 -239 -969 -966]

In [117]:
def info_matrix(matrix):
    if type(matrix) == type(np.array(0)):
        print(f"Maximum value of the matrix: {matrix.max()}")
        print(f"Maximum value per column: {matrix.max(axis = 0)}")
        print(f"Maximum value per line: {matrix.max(axis = 1)}")
        print(f"Minimum value of the matrix: {matrix.min()}")
        print(f"Minimum value per column: {matrix.min(axis = 0)}")
        print(f"Minimum value per line: {matrix.min(axis = 1)}")
    else:
        print("This isn't a matrix")

In [118]:
ex16 = np.random.randint(-1000,1000,50).reshape(10,5)
info_matrix(ex16)

Maximum value of the matrix: 980
Maximum value per column: [836 980 977 781 794]
Maximum value per line: [794 796 781 744 977 980 853 756 980 787]
Minimum value of the matrix: -967
Minimum value per column: [-967 -948 -607 -906 -927]
Minimum value per line: [-948 -245   40 -607 -832 -546 -906 -967 -735 -936]


In [119]:
info_matrix([22,3,4,5,])

This isn't a matrix


----------------------------------------------------------------------------------------------------------------------------
## Exercise 17:
Based on the array defined below, obtain your average, median, variance, and standard deviation.

    import numpy as np
    arr = np.random.normal(40,0.5,size = (300))
    
    Average: np.mean();

    Median: np.median();

    Standard deviation: np.std();

    Variance: np.var().

In [129]:
ex17 = np.random.normal(40,0.5,size = (300))

In [130]:
print(f"Average: {np.mean(ex17)}")
print(f"Median: {np.median(ex17)}")
print(f"Variance: {np.var(ex17)}")
print(f"Standard deviation: {np.std(ex17)}")

Average: 39.95961312412804
Median: 39.99326985708161
Variance: 0.2142054259426366
Standard deviation: 0.4628233204394919


----------------------------------------------------------------------------------------------------------------------------
## Exercise 18:
Based on the arrays defined below, obtain the covariance matrix and the correlation matrix.

    import numpy as np
    x = np.random.rand(100)
    y = np.random.uniform(size=100)


Tip: use np.corrcoef() and np.cov().

In [134]:
ex18X = np.random.rand(100)
ex18Y = np.random.uniform(size=100)

In [137]:
print(f"Covariance: {np.cov(ex18X, ex18Y)}")
print()
print(f"Correlation matrix: {np.corrcoef(ex18X, ex18Y)}")

Covariance: [[ 0.08769635 -0.00893483]
 [-0.00893483  0.07969743]]

Correlation matrix: [[ 1.         -0.10687436]
 [-0.10687436  1.        ]]


----------------------------------------------------------------------------------------------------------------------------
## Exercise 19: 
Get the index of the maximum value of array A.

    A = np.array([[11, 15, 33, 105],
                  [1, 140, 45, 90],
                  [67, 230, 78, 99]])


Tip: use np.argmax() or array.argmax().

In [138]:
ex19 = np.array([[11, 15, 33, 105],
              [1, 140, 45, 90],
              [67, 230, 78, 99]])

In [139]:
ex19.argmax()

9

----------------------------------------------------------------------------------------------------------------------------
## Exercise 20:
Get the index of the minimum value of array B.


    B = np.array([
        [73, 22, 20, 62,  3],
        [68, 84, 27, 59, 93],
        [48, 52,  4, 55, 50],
        [42, 23, 63, 67,  4],
        [44, 30, 41, 31, 29]])


Tip: use np.argmin() or array.argmin().

In [140]:
ex20 = np.array([
    [73, 22, 20, 62,  3],
    [68, 84, 27, 59, 93],
    [48, 52,  4, 55, 50],
    [42, 23, 63, 67,  4],
    [44, 30, 41, 31, 29]])

In [141]:
ex20.argmin()

4