In [1]:
import numpy as np

In [2]:
# Creacion de vector en numpy
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

In [4]:
# Forma 1: Elegir elementos de el vector numpy
valoraciones[0][1]

7

In [5]:
# Forma 2: Elegir elementos de el vector numpy
valoraciones[0,1]

7

In [7]:
# Array de mas de una dimension
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [9]:
# Forma de elegir elementos de el vector numpy de varia dimenciones
valoraciones2[0,1,2]

5

In [10]:
# Creacion de numpy vacias
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
# operacione arrays del mismo tamaño ("np.ones" nos crea un array llemos de 1) Pero no lo guardo a menos que lo iguale
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [20]:
# calcular la media del array entero
np.mean(valoraciones2)

6.458333333333333

In [26]:
# nos da la media de cada indice del vector
np.mean(valoraciones2, axis = 0)

array([[6.        , 7.        , 8.33333333, 4.        ],
       [6.66666667, 7.66666667, 7.33333333, 4.66666667]])

In [27]:
# Convertir una lista en las dimensiones que se quiere 
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [28]:
# calcular la mediana en una columan de un dataframe
#np.median(df["columna1"])

In [30]:
# Array de 2*2 dimenciones con numeros aleatorios del (0-1)
np.random.rand(2,2)

array([[0.36490602, 0.03688289],
       [0.57834415, 0.81968839]])